version: '2'

services:
  web:
    container_name: nirhub_web
    image: nirhub/web
    ports:
      - "80:80"
    restart: always
    volumes:
      - ./nginx.conf:/etc/nginx/conf.d/nginx.conf"
      - ./main.nginx.conf:/etc/nginx/nginx.conf
